task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 10
remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/bdd100k/images/100k/train/
    ann_file: /data/coco_labels/bdd100k_labels_images_train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 1
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/bdd100k/images/100k/val/
    ann_file: /data/coco_labels/bdd100k_labels_images_val_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 1
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
